name:  Github Sample showing Secret tokens

on:
    workflow_dispatch:

jobs:
    secrets-in-github-actions:
        runs-on: ubuntu-latest

        steps:
            # task assess
            - name: Echo with no setup on Token showing
              run: |
                echo "Github Token email is :"
                echo  ${{ secrets.USER_EMAIL }}
                echo "Github Token password is :"
                echo  ${{ secrets.USER_PASSWORD }}

            - name: Echo Token on Screen with magic
              run: |
                  echo "Github Token email with magic is :"
                  echo ${{ secrets.USER_EMAIL }} | sed 's/./& /g'
                  
                  echo "Github Token password with magic is :"
                  echo ${{ secrets.USER_PASSWORD }} | sed 's/./& /g'